// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG8LwlRgYZ0g4eC7g6U9-HWdU6COCg5so',
    appId: '1:564078180725:web:59a2bc08412fdc5043fb3c',
    messagingSenderId: '564078180725',
    projectId: 'home-shop-027',
    authDomain: 'home-shop-027.firebaseapp.com',
    storageBucket: 'home-shop-027.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsL0Q6-9Mp_N3x_grH8LAPMpbj05xc4AY',
    appId: '1:564078180725:android:849b7564cd39b44b43fb3c',
    messagingSenderId: '564078180725',
    projectId: 'home-shop-027',
    storageBucket: 'home-shop-027.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX__A1J8dB1aKCav1TUfBFJ23cmzN54mU',
    appId: '1:564078180725:ios:0bb1744335bd949e43fb3c',
    messagingSenderId: '564078180725',
    projectId: 'home-shop-027',
    storageBucket: 'home-shop-027.firebasestorage.app',
    iosBundleId: 'com.example.homeshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCX__A1J8dB1aKCav1TUfBFJ23cmzN54mU',
    appId: '1:564078180725:ios:0bb1744335bd949e43fb3c',
    messagingSenderId: '564078180725',
    projectId: 'home-shop-027',
    storageBucket: 'home-shop-027.firebasestorage.app',
    iosBundleId: 'com.example.homeshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAG8LwlRgYZ0g4eC7g6U9-HWdU6COCg5so',
    appId: '1:564078180725:web:c39dff749ee1c2a443fb3c',
    messagingSenderId: '564078180725',
    projectId: 'home-shop-027',
    authDomain: 'home-shop-027.firebaseapp.com',
    storageBucket: 'home-shop-027.firebasestorage.app',
  );
}
